name: Link Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "26 02 * * 2"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.1.0
        with:
          args: --verbose --no-progress **/*.md **/*.html --base https://datacarpentry.org/semester-biology
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
